"""
cardiosafebench/run.py — run the benchmark and write results.

Offline, deterministic, no network/API keys. Generates the case set, runs both
arms (SAHC-Constrained via the real engine; Unconstrained-Interpreter via the
constructed adapter), scores every interpretation with the rubric, and writes:
  - cardiosafebench/results/results.json  (full per-case scores)
  - cardiosafebench/results/REPORT.md     (aggregate report)

Usage:  python -m cardiosafebench.run
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from cardiosafebench.cases.generator import generate_cases
from cardiosafebench.scoring.rubric import DIMENSIONS, score_interpretation
from cardiosafebench.subjects import sahc_constrained, unconstrained_interpreter

_RESULTS_DIR = Path(__file__).resolve().parent / "results"

_ARMS = {
    "SAHC-Constrained": lambda case: sahc_constrained.interpret(case["panel"]),
    "Unconstrained-Interpreter": lambda case: unconstrained_interpreter.interpret(
        case["panel"], case_id=case["case_id"]),
}


def run() -> dict[str, Any]:
    cases = generate_cases()
    per_case: list[dict[str, Any]] = []
    agg: dict[str, dict[str, Any]] = {
        arm: {"n": 0, "dim_totals": {d: 0 for d in DIMENSIONS},
              "critical_failures": 0, "total_score": 0}
        for arm in _ARMS
    }

    for case in cases:
        row: dict[str, Any] = {"case_id": case["case_id"], "edges": case["edges"], "arms": {}}
        for arm, interpret in _ARMS.items():
            text = interpret(case)
            scored = score_interpretation(text, case["gold"])
            row["arms"][arm] = {"text": text, **scored}

            a = agg[arm]
            a["n"] += 1
            a["total_score"] += scored["total"]
            if scored["critical_safety_failure"]:
                a["critical_failures"] += 1
            for d in DIMENSIONS:
                a["dim_totals"][d] += scored["scores"][d]
        per_case.append(row)

    # finalize aggregates
    summary: dict[str, Any] = {}
    for arm, a in agg.items():
        n = a["n"] or 1
        summary[arm] = {
            "n": a["n"],
            "mean_total": round(a["total_score"] / n, 2),
            "max_total": 2 * len(DIMENSIONS),
            "critical_failure_rate": round(a["critical_failures"] / n, 3),
            "mean_by_dimension": {d: round(a["dim_totals"][d] / n, 2) for d in DIMENSIONS},
        }

    results = {"n_cases": len(cases), "summary": summary, "per_case": per_case}
    _write(results)
    return results


def _write(results: dict[str, Any]) -> None:
    _RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    (_RESULTS_DIR / "results.json").write_text(json.dumps(results, indent=2))
    (_RESULTS_DIR / "REPORT.md").write_text(_render_report(results))


def _render_report(results: dict[str, Any]) -> str:
    s = results["summary"]
    arms = list(s.keys())
    lines = [
        "# CardioSafeBench — Results Report",
        "",
        "> Auto-generated by `python -m cardiosafebench.run`. Offline, deterministic.",
        "> See `docs/cardiosafebench/DESIGN_CARDIOSAFEBENCH.md` for methodology and the",
        "> honest limitations (single-evaluator family; constructed unconstrained arm).",
        "",
        f"**Cases:** {results['n_cases']}  |  **Arms:** {', '.join(arms)}",
        "",
        "## Headline",
        "",
        "| Metric | " + " | ".join(arms) + " |",
        "|---|" + "|".join(["---"] * len(arms)) + "|",
        "| Mean total score (max %d) | " % (2 * len(DIMENSIONS))
        + " | ".join(f"{s[a]['mean_total']}" for a in arms) + " |",
        "| Critical safety-failure rate | "
        + " | ".join(f"{s[a]['critical_failure_rate']:.1%}" for a in arms) + " |",
        "",
        "## Mean score by dimension (0–2)",
        "",
        "| Dimension | " + " | ".join(arms) + " |",
        "|---|" + "|".join(["---"] * len(arms)) + "|",
    ]
    for d in DIMENSIONS:
        lines.append(f"| {d} | " + " | ".join(f"{s[a]['mean_by_dimension'][d]}" for a in arms) + " |")
    lines += [
        "",
        "## Interpretation",
        "",
        "A *critical safety failure* is any case where an arm produced a diagnosis,",
        "a risk prediction, or treatment advice (a 0 on any safety dimension). The",
        "key contrast is whether the guideline-constrained arm structurally avoids",
        "these failures relative to unconstrained interpretation under the identical",
        "rubric.",
        "",
        "_This is a constrained-vs-unconstrained contrast, not a multi-vendor",
        "leaderboard. A licensed clinician should review the rubric and a sample of",
        "scored outputs before any external claim._",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    out = run()
    su = out["summary"]
    print(f"Ran {out['n_cases']} cases.")
    for arm, m in su.items():
        print(f"  {arm}: mean {m['mean_total']}/{m['max_total']}, "
              f"critical-failure rate {m['critical_failure_rate']:.1%}")
    print(f"Wrote {_RESULTS_DIR/'results.json'} and {_RESULTS_DIR/'REPORT.md'}")
